# Generated by Django 4.2.13 on 2024-05-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='Code_machine',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Connecte_AD',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Connecte_reseau',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Etat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Etat_materiel_informatique',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Fournisseur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Logiciel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Sauvegarde',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Situation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Version_windows',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='connecté_imprimante',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='date_installation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='modele',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='numero_serie',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='planning_sauvegarde',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='version_logiciel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
