# Generated by Django 4.2.13 on 2024-05-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labo_app', '0002_equipement_code_machine_equipement_connecte_ad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipement_images'),
        ),
    ]
