# Generated by Django 4.2.13 on 2024-05-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labo_app', '0004_alter_equipement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='role',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('analyst', 'Analyst'), ('Technicien', 'Technicien')], default='analyst', max_length=30),
        ),
    ]
