# Generated by Django 4.2.13 on 2024-06-03 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Labo_app', '0005_alter_employe_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
